[package]
name = "rust-and-select"
version = "0.1.0"
authors = ["Pierre Jambet <pierre.jambet@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"